#!/bin/bash

# ---------------------------------------------------------------
# TODO 
# besoin de loop sur tous les book.toml
# bien faire les ln avec les scripts et les media sur tous les dossiers dans book/
# revoir les ./../media (qui ne marchent pas en local de toute facon) dans les fichier md > media/
# créer la version francaise et tester la redirection de langue (la page doit exister, obligatoire)

# ---------------------------------------------------------------
# virtual env creation
python3 -m venv venv
source venv/bin/activate

# ---------------------------------------------------------------
# requirements
pip install -r requirements.txt --no-input

# ---------------------------------------------------------------
# variables declaration
ROOT=${PWD}

# ---------------------------------------------------------------
# Save previous book
if [ -d "${ROOT}/book" ]; then
    rm -rf ${ROOT}/book.previous_build || true
    mv ${ROOT}/book ${ROOT}/book.previous_build
fi

# ---------------------------------------------------------------
# Pre-build script
echo "[ WEBSITE : PRE-BUILD SCRIPT ]"
python3 -m ${ROOT}/script/pre_build

# ---------------------------------------------------------------
# BUILD SCRIPTS
echo "[ WEBSITE : BUILD ] "
# find all folders under ./src
for folder in $(find src -type d); do
    # find all the book.toml files and execute the build
    if [ -f "${folder}/book.toml" ]; then
        # Replace "src" with "book"
        output_dir="${folder/src/book}"
        echo "Building: ${ROOT}/${folder} -> ${ROOT}/${output_dir}"
        mdbook build "${ROOT}/${folder}" -d "${ROOT}/${output_dir}"
    fi
done

# ---------------------------------------------------------------
# POST BUILD SCRIPTS
echo "[ WEBSITE : POST-BUILD SCRIPT ]"
python3 -m ${ROOT}/script/post_build














# remove unneccessary output folders (https:)
#for folder in $(find book -type d);
#do
#    foldername=$(basename $folder)
#    if [[ "${foldername}" == "https:" ]] || [[ "${foldername}" == "http:" ]]; then
#        rm -rf "${folder}"
#    fi
#done

# all of the html pages are created, we can build the sitemap
#python3 -m generate_sitemap.py || true
# add the dropdown "Version" on each book/**/*.html page generated by mdbook
# python3 -m version.py || true
# add the dropdown "Language" on each book/**/*.html page generated by mdbook
# python3 -m language.py || true
# add css link
#python3 -m custom-css.py || true
# add css link
#python3 -m custom-js.py || true
# update the navigation summary
#python3 -m nav-summary.py || true
## update summary title and subtitle
#python3 -m summary_title.py || true
# fix link format (remove '.html' endings for external links) on each book/**/*.html page generated by mdbook
#python3 -m link.py  || true # must be after rating to prevent the top title to have a subtitle "user find this page useful !"
# update the home page
#python3 -m home.py || true
# update the dev team page
#python3 -m devteam.py || true
# update the roadmap page
#python3 -m roadmap.py || true
# update lets make a game page
#python3 -m lets_make_a_game.py || true
# update installation page
#python3 -m installation.py || true
# update rpg power forge overview page
#python3 -m overview.py || true
# update the footer part
#python3 -m footer.py || true
# update community join button
#python3 -m join-community.py || true
# update devlog embedded videos
#python3 -m devlogs.py || true
# update features progress
#python3 -m features.py || true

# HERO PAGE ADDITION HERE
# add hero page
#cp ${root_dir}/resources/hero.html ${root_dir}/book/index.html
# add links for home page to work (assuming we have /doc at least)
#ln -s ${root_dir}/book/doc/css ${root_dir}/book/css
#ln -s ${root_dir}/book/doc/FontAwesome ${root_dir}/book/FontAwesome
#ln -s ${root_dir}/book/doc/fonts ${root_dir}/book/fonts

# add link thumbnails (a bit long to make)
#python3 -m thumbnail.py
# update favicons
#python3 -m favicon.py || true

#cd ${root_dir}

## zip user manual resources files
#cd ${root_dir}/media/
#zip -r user_resources.zip user_resources || true

#cd ${root_dir}

# process remaining output folders
#for folder in $(find book -type d);
#do
    # process folder
    # add folders links (css, js, media, ...)
#    ln -s ${root_dir}/media/ ${root_dir}/${folder}/media
#    ln -s ${root_dir}/custom-js/ ${root_dir}/${folder}/custom-js
#    ln -s ${root_dir}/custom-css/ ${root_dir}/${folder}/custom-css
#done

# ---------------------------------------------------------------
# WHATS NEW MARKDOWN
#input_md=${root_dir}/src/doc/latest_news.md
#output_md=${root_dir}/book/doc/latest_news.md
#output_hash=${output_md}.sha256
#cp ${input_md} ${output_md}
#sha256sum ${output_md} | awk '{print $1}' > ${output_hash}

# ---------------------------------------------------------------
# WEBSITE METADATA
# Now the website is built, we can add metadata files
# robots.txt
#cp ${root_dir}/resources/robots.txt ${root_dir}/book/robots.txt

# ---------------------------------------------------------------
# LARGE FILE DOWNLOAD
#echo "[ GIT LFS CHECKOUT PART ] "
#cd ${root_dir}
# define $HOME for the user (www-data) 
#export HOME=/home/www-data
#git lfs install --force && git lfs fetch && git lfs checkout


# ---------------------------------------------------------------
# desactivate the virtual env
deactivate
