
# =========================================================
# import section
import re 
import sys 
import os 
import time
from pathlib import Path

from config import config


# =========================================================
# constant values
BOOK_ROOT = "/home/www-data/rpgpowerforge/book"
CSS_ROOT = "/home/www-data/rpgpowerforge/book/custom-css"


# =========================================================
# set external links
def custom_css(filepath, content):

    # add custom .css scripts at the end of the file
    css_links = []

    common_list = config.css_common_list
    black_list = config.css_black_list

    # -----------------------------------------------------------------
    # iterate all files, find css files
    for css_filepath in Path(CSS_ROOT).rglob("*.css"):

        css_webpath = str(css_filepath).replace(BOOK_ROOT, "https://rpgpowerforge.com")

        # skip black list css files
        if css_filepath.name in black_list:
            continue

        # add if in common list
        if css_filepath.name in common_list:
            css_links.append(f"<link rel=\"stylesheet\" href=\"custom-css/{css_webpath}\">")

        # also add if the css file has the same name as the current html file
        else:

            html_filename = filepath.stem
            # index and home are the same page
            if html_filename == "index":
                html_filename = "home"

            if css_filepath.stem == html_filename:
                css_links.append(f"<link rel=\"stylesheet\" href=\"custom-css/{css_webpath}\">")

    str_to_replace = "<!-- Custom theme stylesheets -->"
    str_replacement = "<!-- Custom theme stylesheets -->\n" + '\n'.join(css_links)

    return content.replace(str_to_replace, str_replacement)



# =========================================================
# entry point
def main():
    
    # -----------------------------------------------------------------
    # init
    start = time.time()

    # -----------------------------------------------------------------
    # try to run all pre build functions
    try:
        
        # -----------------------------------------------------------------
        # iterate all files, find html files
        for filepath in Path(BOOK_ROOT).rglob("*.html"):
                    
            # -----------------------------------------------------------------
            # md file !
            print(filepath)
            content = ""
            with open(filepath, 'r', encoding="utf8") as f:
                content = f.read()

            # -----------------------------------------------------------------
            # general settings
            content = custom_css(filepath, content)

            # -----------------------------------------------------------------
            # name specific settings
            #if (filepath.name == "xxx.html"): content = yyy(content)

            # -----------------------------------------------------------------                    
            # Save the updated content
            with open(filepath, 'w', encoding="utf8") as f:
                f.write(content)

            # add css link
            #python3 -m custom-js.py || true
            # update the navigation summary
            #python3 -m nav-summary.py || true
            ## update summary title and subtitle
            #python3 -m summary_title.py || true
            # fix link format (remove '.html' endings for external links) on each book/**/*.html page generated by mdbook
            #python3 -m link.py  || true # must be after rating to prevent the top title to have a subtitle "user find this page useful !"
            # update the home page
            #python3 -m home.py || true
            # update the dev team page
            #python3 -m devteam.py || true
            # update the roadmap page
            #python3 -m roadmap.py || true
            # update lets make a game page
            #python3 -m lets_make_a_game.py || true
            # update installation page
            #python3 -m installation.py || true
            # update rpg power forge overview page
            #python3 -m overview.py || true
            # update the footer part
            #python3 -m footer.py || true
            # update community join button
            #python3 -m join-community.py || true
            # update devlog embedded videos
            #python3 -m devlogs.py || true
            # update features progress
            #python3 -m features.py || true


    except Exception as e:
        print(e)

    finally:
        # duration & exit
        end = time.time()
        print(f"Script duration : {str(round(end - start, 1))} sec")
        return 0

# =========================================================
# entry point
if __name__ == "__main__":
    sys.exit(main())
